// Code generated by ent, DO NOT EDIT.

package modelname

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Arash-Afshar/pagoda-tailwindcss/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ModelName {
	return predicate.ModelName(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ModelName {
	return predicate.ModelName(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ModelName {
	return predicate.ModelName(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ModelName {
	return predicate.ModelName(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ModelName {
	return predicate.ModelName(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ModelName {
	return predicate.ModelName(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ModelName {
	return predicate.ModelName(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ModelName {
	return predicate.ModelName(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ModelName {
	return predicate.ModelName(sql.FieldLTE(FieldID, id))
}

// FieldName applies equality check predicate on the "field_name" field. It's identical to FieldNameEQ.
func FieldName(v string) predicate.ModelName {
	return predicate.ModelName(sql.FieldEQ(FieldFieldName, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelName {
	return predicate.ModelName(sql.FieldEQ(FieldCreatedAt, v))
}

// FieldNameEQ applies the EQ predicate on the "field_name" field.
func FieldNameEQ(v string) predicate.ModelName {
	return predicate.ModelName(sql.FieldEQ(FieldFieldName, v))
}

// FieldNameNEQ applies the NEQ predicate on the "field_name" field.
func FieldNameNEQ(v string) predicate.ModelName {
	return predicate.ModelName(sql.FieldNEQ(FieldFieldName, v))
}

// FieldNameIn applies the In predicate on the "field_name" field.
func FieldNameIn(vs ...string) predicate.ModelName {
	return predicate.ModelName(sql.FieldIn(FieldFieldName, vs...))
}

// FieldNameNotIn applies the NotIn predicate on the "field_name" field.
func FieldNameNotIn(vs ...string) predicate.ModelName {
	return predicate.ModelName(sql.FieldNotIn(FieldFieldName, vs...))
}

// FieldNameGT applies the GT predicate on the "field_name" field.
func FieldNameGT(v string) predicate.ModelName {
	return predicate.ModelName(sql.FieldGT(FieldFieldName, v))
}

// FieldNameGTE applies the GTE predicate on the "field_name" field.
func FieldNameGTE(v string) predicate.ModelName {
	return predicate.ModelName(sql.FieldGTE(FieldFieldName, v))
}

// FieldNameLT applies the LT predicate on the "field_name" field.
func FieldNameLT(v string) predicate.ModelName {
	return predicate.ModelName(sql.FieldLT(FieldFieldName, v))
}

// FieldNameLTE applies the LTE predicate on the "field_name" field.
func FieldNameLTE(v string) predicate.ModelName {
	return predicate.ModelName(sql.FieldLTE(FieldFieldName, v))
}

// FieldNameContains applies the Contains predicate on the "field_name" field.
func FieldNameContains(v string) predicate.ModelName {
	return predicate.ModelName(sql.FieldContains(FieldFieldName, v))
}

// FieldNameHasPrefix applies the HasPrefix predicate on the "field_name" field.
func FieldNameHasPrefix(v string) predicate.ModelName {
	return predicate.ModelName(sql.FieldHasPrefix(FieldFieldName, v))
}

// FieldNameHasSuffix applies the HasSuffix predicate on the "field_name" field.
func FieldNameHasSuffix(v string) predicate.ModelName {
	return predicate.ModelName(sql.FieldHasSuffix(FieldFieldName, v))
}

// FieldNameEqualFold applies the EqualFold predicate on the "field_name" field.
func FieldNameEqualFold(v string) predicate.ModelName {
	return predicate.ModelName(sql.FieldEqualFold(FieldFieldName, v))
}

// FieldNameContainsFold applies the ContainsFold predicate on the "field_name" field.
func FieldNameContainsFold(v string) predicate.ModelName {
	return predicate.ModelName(sql.FieldContainsFold(FieldFieldName, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelName {
	return predicate.ModelName(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelName {
	return predicate.ModelName(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelName {
	return predicate.ModelName(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelName {
	return predicate.ModelName(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelName {
	return predicate.ModelName(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelName {
	return predicate.ModelName(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelName {
	return predicate.ModelName(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelName {
	return predicate.ModelName(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ModelName {
	return predicate.ModelName(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ModelName {
	return predicate.ModelName(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelName) predicate.ModelName {
	return predicate.ModelName(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelName) predicate.ModelName {
	return predicate.ModelName(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelName) predicate.ModelName {
	return predicate.ModelName(sql.NotPredicates(p))
}
