version: "3"

services:
  cache:
    image: "redis:alpine"
    container_name: pagoda_cache
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:
