http:
  hostname: "localhost"
  port: 8000
  readTimeout: "5s"
  writeTimeout: "10s"
  idleTimeout: "2m"
  tls:
    enabled: false
    certificate: ""
    key: ""

app:
  name: "Pagoda"
  environment: "local"
  # Change this on any live environments
  encryptionKey: "changemechangemechangemechangeme"
  timeout: "20s"
  passwordToken:
      expiration: "60m"
      length: 64
  emailVerificationTokenExpiration: "12h"

cache:
  redis:
    hostname: "localhost"
    port: 6379
    password: ""
    database: 0
    testDatabase: 1
  otter:
    capacity: 100000

  expiration:
    staticFile: "4380h"
    page: "24h"

database:
  driver: "sqlite3"
  connection: "dbs/main.db?_journal=WAL&_timeout=5000&_fk=true"
  testConnection: ":memory:?_journal=WAL&_timeout=5000&_fk=true"

tasks:
  goroutines: 1
  releaseAfter: "15m"
  cleanupInterval: "1h"

stripe:
  url: "https://api.stripe.com"
  key: "change-me"
  webhookSecret: "change-me"

ais:
  - name: "test"
    url: ""
    key: "change-me"
  - name: "ollama"
    url: "http://localhost:11434"
    key: "change-me"

mail:
  hostname: "localhost"
  port: 25
  user: "admin"
  password: "admin"
  fromAddress: "admin@localhost"
