// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ModelNamesColumns holds the columns for the "model_names" table.
	ModelNamesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "field_name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_model_names", Type: field.TypeInt},
	}
	// ModelNamesTable holds the schema information for the "model_names" table.
	ModelNamesTable = &schema.Table{
		Name:       "model_names",
		Columns:    ModelNamesColumns,
		PrimaryKey: []*schema.Column{ModelNamesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "model_names_users_ModelNames",
				Columns:    []*schema.Column{ModelNamesColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PasswordTokensColumns holds the columns for the "password_tokens" table.
	PasswordTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "password_token_user", Type: field.TypeInt},
	}
	// PasswordTokensTable holds the schema information for the "password_tokens" table.
	PasswordTokensTable = &schema.Table{
		Name:       "password_tokens",
		Columns:    PasswordTokensColumns,
		PrimaryKey: []*schema.Column{PasswordTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "password_tokens_users_user",
				Columns:    []*schema.Column{PasswordTokensColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PricesColumns holds the columns for the "prices" table.
	PricesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "stripe_id", Type: field.TypeString},
		{Name: "amount", Type: field.TypeInt},
		{Name: "quantity", Type: field.TypeInt},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"one-time", "monthly", "annual"}, Default: "one-time"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "product_prices", Type: field.TypeInt},
		{Name: "user_prices", Type: field.TypeInt},
	}
	// PricesTable holds the schema information for the "prices" table.
	PricesTable = &schema.Table{
		Name:       "prices",
		Columns:    PricesColumns,
		PrimaryKey: []*schema.Column{PricesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "prices_products_prices",
				Columns:    []*schema.Column{PricesColumns[6]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "prices_users_Prices",
				Columns:    []*schema.Column{PricesColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "stripe_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_products", Type: field.TypeInt},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "products_users_Products",
				Columns:    []*schema.Column{ProductsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "verified", Type: field.TypeBool, Default: false},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "user"}, Default: "user"},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ModelNamesTable,
		PasswordTokensTable,
		PricesTable,
		ProductsTable,
		UsersTable,
	}
)

func init() {
	ModelNamesTable.ForeignKeys[0].RefTable = UsersTable
	PasswordTokensTable.ForeignKeys[0].RefTable = UsersTable
	PricesTable.ForeignKeys[0].RefTable = ProductsTable
	PricesTable.ForeignKeys[1].RefTable = UsersTable
	ProductsTable.ForeignKeys[0].RefTable = UsersTable
}
