// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Arash-Afshar/pagoda-tailwindcss/ent/ai"
	"github.com/Arash-Afshar/pagoda-tailwindcss/ent/user"
)

// AICreate is the builder for creating a AI entity.
type AICreate struct {
	config
	mutation *AIMutation
	hooks    []Hook
}

// SetAiClientName sets the "ai_client_name" field.
func (ac *AICreate) SetAiClientName(s string) *AICreate {
	ac.mutation.SetAiClientName(s)
	return ac
}

// SetPrompt sets the "prompt" field.
func (ac *AICreate) SetPrompt(s string) *AICreate {
	ac.mutation.SetPrompt(s)
	return ac
}

// SetStatus sets the "status" field.
func (ac *AICreate) SetStatus(a ai.Status) *AICreate {
	ac.mutation.SetStatus(a)
	return ac
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ac *AICreate) SetNillableStatus(a *ai.Status) *AICreate {
	if a != nil {
		ac.SetStatus(*a)
	}
	return ac
}

// SetResult sets the "result" field.
func (ac *AICreate) SetResult(b []byte) *AICreate {
	ac.mutation.SetResult(b)
	return ac
}

// SetCreatedAt sets the "created_at" field.
func (ac *AICreate) SetCreatedAt(t time.Time) *AICreate {
	ac.mutation.SetCreatedAt(t)
	return ac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ac *AICreate) SetNillableCreatedAt(t *time.Time) *AICreate {
	if t != nil {
		ac.SetCreatedAt(*t)
	}
	return ac
}

// SetCompletedAt sets the "completed_at" field.
func (ac *AICreate) SetCompletedAt(t time.Time) *AICreate {
	ac.mutation.SetCompletedAt(t)
	return ac
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (ac *AICreate) SetNillableCompletedAt(t *time.Time) *AICreate {
	if t != nil {
		ac.SetCompletedAt(*t)
	}
	return ac
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ac *AICreate) SetUserID(id int) *AICreate {
	ac.mutation.SetUserID(id)
	return ac
}

// SetUser sets the "user" edge to the User entity.
func (ac *AICreate) SetUser(u *User) *AICreate {
	return ac.SetUserID(u.ID)
}

// Mutation returns the AIMutation object of the builder.
func (ac *AICreate) Mutation() *AIMutation {
	return ac.mutation
}

// Save creates the AI in the database.
func (ac *AICreate) Save(ctx context.Context) (*AI, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AICreate) SaveX(ctx context.Context) *AI {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AICreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AICreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AICreate) defaults() {
	if _, ok := ac.mutation.Status(); !ok {
		v := ai.DefaultStatus
		ac.mutation.SetStatus(v)
	}
	if _, ok := ac.mutation.Result(); !ok {
		v := ai.DefaultResult
		ac.mutation.SetResult(v)
	}
	if _, ok := ac.mutation.CreatedAt(); !ok {
		v := ai.DefaultCreatedAt()
		ac.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AICreate) check() error {
	if _, ok := ac.mutation.AiClientName(); !ok {
		return &ValidationError{Name: "ai_client_name", err: errors.New(`ent: missing required field "AI.ai_client_name"`)}
	}
	if v, ok := ac.mutation.AiClientName(); ok {
		if err := ai.AiClientNameValidator(v); err != nil {
			return &ValidationError{Name: "ai_client_name", err: fmt.Errorf(`ent: validator failed for field "AI.ai_client_name": %w`, err)}
		}
	}
	if _, ok := ac.mutation.Prompt(); !ok {
		return &ValidationError{Name: "prompt", err: errors.New(`ent: missing required field "AI.prompt"`)}
	}
	if v, ok := ac.mutation.Prompt(); ok {
		if err := ai.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "AI.prompt": %w`, err)}
		}
	}
	if _, ok := ac.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AI.status"`)}
	}
	if v, ok := ac.mutation.Status(); ok {
		if err := ai.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AI.status": %w`, err)}
		}
	}
	if _, ok := ac.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "AI.result"`)}
	}
	if _, ok := ac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AI.created_at"`)}
	}
	if len(ac.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AI.user"`)}
	}
	return nil
}

func (ac *AICreate) sqlSave(ctx context.Context) (*AI, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AICreate) createSpec() (*AI, *sqlgraph.CreateSpec) {
	var (
		_node = &AI{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(ai.Table, sqlgraph.NewFieldSpec(ai.FieldID, field.TypeInt))
	)
	if value, ok := ac.mutation.AiClientName(); ok {
		_spec.SetField(ai.FieldAiClientName, field.TypeString, value)
		_node.AiClientName = value
	}
	if value, ok := ac.mutation.Prompt(); ok {
		_spec.SetField(ai.FieldPrompt, field.TypeString, value)
		_node.Prompt = value
	}
	if value, ok := ac.mutation.Status(); ok {
		_spec.SetField(ai.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := ac.mutation.Result(); ok {
		_spec.SetField(ai.FieldResult, field.TypeBytes, value)
		_node.Result = value
	}
	if value, ok := ac.mutation.CreatedAt(); ok {
		_spec.SetField(ai.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ac.mutation.CompletedAt(); ok {
		_spec.SetField(ai.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = value
	}
	if nodes := ac.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ai.UserTable,
			Columns: []string{ai.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_ais = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AICreateBulk is the builder for creating many AI entities in bulk.
type AICreateBulk struct {
	config
	err      error
	builders []*AICreate
}

// Save creates the AI entities in the database.
func (acb *AICreateBulk) Save(ctx context.Context) ([]*AI, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*AI, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AIMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AICreateBulk) SaveX(ctx context.Context) []*AI {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AICreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AICreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
