// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Arash-Afshar/pagoda-tailwindcss/ent/modelname"
	"github.com/Arash-Afshar/pagoda-tailwindcss/ent/predicate"
)

// ModelNameDelete is the builder for deleting a ModelName entity.
type ModelNameDelete struct {
	config
	hooks    []Hook
	mutation *ModelNameMutation
}

// Where appends a list predicates to the ModelNameDelete builder.
func (mnd *ModelNameDelete) Where(ps ...predicate.ModelName) *ModelNameDelete {
	mnd.mutation.Where(ps...)
	return mnd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mnd *ModelNameDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mnd.sqlExec, mnd.mutation, mnd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mnd *ModelNameDelete) ExecX(ctx context.Context) int {
	n, err := mnd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mnd *ModelNameDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(modelname.Table, sqlgraph.NewFieldSpec(modelname.FieldID, field.TypeInt))
	if ps := mnd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mnd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mnd.mutation.done = true
	return affected, err
}

// ModelNameDeleteOne is the builder for deleting a single ModelName entity.
type ModelNameDeleteOne struct {
	mnd *ModelNameDelete
}

// Where appends a list predicates to the ModelNameDelete builder.
func (mndo *ModelNameDeleteOne) Where(ps ...predicate.ModelName) *ModelNameDeleteOne {
	mndo.mnd.mutation.Where(ps...)
	return mndo
}

// Exec executes the deletion query.
func (mndo *ModelNameDeleteOne) Exec(ctx context.Context) error {
	n, err := mndo.mnd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{modelname.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mndo *ModelNameDeleteOne) ExecX(ctx context.Context) {
	if err := mndo.Exec(ctx); err != nil {
		panic(err)
	}
}
