// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Arash-Afshar/pagoda-tailwindcss/ent/modelname"
	"github.com/Arash-Afshar/pagoda-tailwindcss/ent/predicate"
	"github.com/Arash-Afshar/pagoda-tailwindcss/ent/user"
)

// ModelNameQuery is the builder for querying ModelName entities.
type ModelNameQuery struct {
	config
	ctx        *QueryContext
	order      []modelname.OrderOption
	inters     []Interceptor
	predicates []predicate.ModelName
	withUser   *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ModelNameQuery builder.
func (mnq *ModelNameQuery) Where(ps ...predicate.ModelName) *ModelNameQuery {
	mnq.predicates = append(mnq.predicates, ps...)
	return mnq
}

// Limit the number of records to be returned by this query.
func (mnq *ModelNameQuery) Limit(limit int) *ModelNameQuery {
	mnq.ctx.Limit = &limit
	return mnq
}

// Offset to start from.
func (mnq *ModelNameQuery) Offset(offset int) *ModelNameQuery {
	mnq.ctx.Offset = &offset
	return mnq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mnq *ModelNameQuery) Unique(unique bool) *ModelNameQuery {
	mnq.ctx.Unique = &unique
	return mnq
}

// Order specifies how the records should be ordered.
func (mnq *ModelNameQuery) Order(o ...modelname.OrderOption) *ModelNameQuery {
	mnq.order = append(mnq.order, o...)
	return mnq
}

// QueryUser chains the current query on the "user" edge.
func (mnq *ModelNameQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: mnq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mnq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mnq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(modelname.Table, modelname.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, modelname.UserTable, modelname.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(mnq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ModelName entity from the query.
// Returns a *NotFoundError when no ModelName was found.
func (mnq *ModelNameQuery) First(ctx context.Context) (*ModelName, error) {
	nodes, err := mnq.Limit(1).All(setContextOp(ctx, mnq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{modelname.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mnq *ModelNameQuery) FirstX(ctx context.Context) *ModelName {
	node, err := mnq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ModelName ID from the query.
// Returns a *NotFoundError when no ModelName ID was found.
func (mnq *ModelNameQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mnq.Limit(1).IDs(setContextOp(ctx, mnq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{modelname.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mnq *ModelNameQuery) FirstIDX(ctx context.Context) int {
	id, err := mnq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ModelName entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ModelName entity is found.
// Returns a *NotFoundError when no ModelName entities are found.
func (mnq *ModelNameQuery) Only(ctx context.Context) (*ModelName, error) {
	nodes, err := mnq.Limit(2).All(setContextOp(ctx, mnq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{modelname.Label}
	default:
		return nil, &NotSingularError{modelname.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mnq *ModelNameQuery) OnlyX(ctx context.Context) *ModelName {
	node, err := mnq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ModelName ID in the query.
// Returns a *NotSingularError when more than one ModelName ID is found.
// Returns a *NotFoundError when no entities are found.
func (mnq *ModelNameQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mnq.Limit(2).IDs(setContextOp(ctx, mnq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{modelname.Label}
	default:
		err = &NotSingularError{modelname.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mnq *ModelNameQuery) OnlyIDX(ctx context.Context) int {
	id, err := mnq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ModelNames.
func (mnq *ModelNameQuery) All(ctx context.Context) ([]*ModelName, error) {
	ctx = setContextOp(ctx, mnq.ctx, ent.OpQueryAll)
	if err := mnq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ModelName, *ModelNameQuery]()
	return withInterceptors[[]*ModelName](ctx, mnq, qr, mnq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mnq *ModelNameQuery) AllX(ctx context.Context) []*ModelName {
	nodes, err := mnq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ModelName IDs.
func (mnq *ModelNameQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mnq.ctx.Unique == nil && mnq.path != nil {
		mnq.Unique(true)
	}
	ctx = setContextOp(ctx, mnq.ctx, ent.OpQueryIDs)
	if err = mnq.Select(modelname.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mnq *ModelNameQuery) IDsX(ctx context.Context) []int {
	ids, err := mnq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mnq *ModelNameQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mnq.ctx, ent.OpQueryCount)
	if err := mnq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mnq, querierCount[*ModelNameQuery](), mnq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mnq *ModelNameQuery) CountX(ctx context.Context) int {
	count, err := mnq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mnq *ModelNameQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mnq.ctx, ent.OpQueryExist)
	switch _, err := mnq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mnq *ModelNameQuery) ExistX(ctx context.Context) bool {
	exist, err := mnq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ModelNameQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mnq *ModelNameQuery) Clone() *ModelNameQuery {
	if mnq == nil {
		return nil
	}
	return &ModelNameQuery{
		config:     mnq.config,
		ctx:        mnq.ctx.Clone(),
		order:      append([]modelname.OrderOption{}, mnq.order...),
		inters:     append([]Interceptor{}, mnq.inters...),
		predicates: append([]predicate.ModelName{}, mnq.predicates...),
		withUser:   mnq.withUser.Clone(),
		// clone intermediate query.
		sql:  mnq.sql.Clone(),
		path: mnq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (mnq *ModelNameQuery) WithUser(opts ...func(*UserQuery)) *ModelNameQuery {
	query := (&UserClient{config: mnq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mnq.withUser = query
	return mnq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FieldName string `json:"field_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ModelName.Query().
//		GroupBy(modelname.FieldFieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mnq *ModelNameQuery) GroupBy(field string, fields ...string) *ModelNameGroupBy {
	mnq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ModelNameGroupBy{build: mnq}
	grbuild.flds = &mnq.ctx.Fields
	grbuild.label = modelname.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FieldName string `json:"field_name,omitempty"`
//	}
//
//	client.ModelName.Query().
//		Select(modelname.FieldFieldName).
//		Scan(ctx, &v)
func (mnq *ModelNameQuery) Select(fields ...string) *ModelNameSelect {
	mnq.ctx.Fields = append(mnq.ctx.Fields, fields...)
	sbuild := &ModelNameSelect{ModelNameQuery: mnq}
	sbuild.label = modelname.Label
	sbuild.flds, sbuild.scan = &mnq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ModelNameSelect configured with the given aggregations.
func (mnq *ModelNameQuery) Aggregate(fns ...AggregateFunc) *ModelNameSelect {
	return mnq.Select().Aggregate(fns...)
}

func (mnq *ModelNameQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mnq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mnq); err != nil {
				return err
			}
		}
	}
	for _, f := range mnq.ctx.Fields {
		if !modelname.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mnq.path != nil {
		prev, err := mnq.path(ctx)
		if err != nil {
			return err
		}
		mnq.sql = prev
	}
	return nil
}

func (mnq *ModelNameQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ModelName, error) {
	var (
		nodes       = []*ModelName{}
		withFKs     = mnq.withFKs
		_spec       = mnq.querySpec()
		loadedTypes = [1]bool{
			mnq.withUser != nil,
		}
	)
	if mnq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, modelname.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ModelName).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ModelName{config: mnq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mnq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mnq.withUser; query != nil {
		if err := mnq.loadUser(ctx, query, nodes, nil,
			func(n *ModelName, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mnq *ModelNameQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*ModelName, init func(*ModelName), assign func(*ModelName, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ModelName)
	for i := range nodes {
		if nodes[i].user_model_names == nil {
			continue
		}
		fk := *nodes[i].user_model_names
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_model_names" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mnq *ModelNameQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mnq.querySpec()
	_spec.Node.Columns = mnq.ctx.Fields
	if len(mnq.ctx.Fields) > 0 {
		_spec.Unique = mnq.ctx.Unique != nil && *mnq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mnq.driver, _spec)
}

func (mnq *ModelNameQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(modelname.Table, modelname.Columns, sqlgraph.NewFieldSpec(modelname.FieldID, field.TypeInt))
	_spec.From = mnq.sql
	if unique := mnq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mnq.path != nil {
		_spec.Unique = true
	}
	if fields := mnq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelname.FieldID)
		for i := range fields {
			if fields[i] != modelname.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mnq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mnq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mnq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mnq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mnq *ModelNameQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mnq.driver.Dialect())
	t1 := builder.Table(modelname.Table)
	columns := mnq.ctx.Fields
	if len(columns) == 0 {
		columns = modelname.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mnq.sql != nil {
		selector = mnq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mnq.ctx.Unique != nil && *mnq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mnq.predicates {
		p(selector)
	}
	for _, p := range mnq.order {
		p(selector)
	}
	if offset := mnq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mnq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ModelNameGroupBy is the group-by builder for ModelName entities.
type ModelNameGroupBy struct {
	selector
	build *ModelNameQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mngb *ModelNameGroupBy) Aggregate(fns ...AggregateFunc) *ModelNameGroupBy {
	mngb.fns = append(mngb.fns, fns...)
	return mngb
}

// Scan applies the selector query and scans the result into the given value.
func (mngb *ModelNameGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mngb.build.ctx, ent.OpQueryGroupBy)
	if err := mngb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ModelNameQuery, *ModelNameGroupBy](ctx, mngb.build, mngb, mngb.build.inters, v)
}

func (mngb *ModelNameGroupBy) sqlScan(ctx context.Context, root *ModelNameQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mngb.fns))
	for _, fn := range mngb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mngb.flds)+len(mngb.fns))
		for _, f := range *mngb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mngb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mngb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ModelNameSelect is the builder for selecting fields of ModelName entities.
type ModelNameSelect struct {
	*ModelNameQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mns *ModelNameSelect) Aggregate(fns ...AggregateFunc) *ModelNameSelect {
	mns.fns = append(mns.fns, fns...)
	return mns
}

// Scan applies the selector query and scans the result into the given value.
func (mns *ModelNameSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mns.ctx, ent.OpQuerySelect)
	if err := mns.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ModelNameQuery, *ModelNameSelect](ctx, mns.ModelNameQuery, mns, mns.inters, v)
}

func (mns *ModelNameSelect) sqlScan(ctx context.Context, root *ModelNameQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mns.fns))
	for _, fn := range mns.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mns.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
